--DROP TABLE IF EXISTS item;

CREATE TABLE IF NOT EXISTS item (
  guid VARCHAR(250) PRIMARY KEY,
  title VARCHAR(250) NULL,
  description VARCHAR(1000) NULL,
  published_date TIMESTAMP NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);